# Generated by Django 4.0 on 2022-07-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='species',
            field=models.CharField(choices=[('SMELT', 'Smelt'), ('PIKE', 'Pike'), ('PERCH', 'Perch'), ('PARKKI', 'Parkki'), ('WHITEFISH', 'Whitefish'), ('ROACH', 'Roach'), ('BREAM', 'Bream')], max_length=35, null=True),
        ),
    ]
